// CATEGORIES
export const FETCH_CATEGORIES_REQUEST = "FETCH_CATEGORIES_REQUEST";
export const FETCH_CATEGORIES_FAILURE = "FETCH_CATEGORIES_FAILURE";
export const FETCH_CATEGORIES_SUCCESS = "FETCH_CATEGORIES_SUCCESS";
export const ADD_CATEGORY_USE_REF = "ADD_CATEGORY_USE_REF";

// CATALOG
export const FETCH_SHOES_REQUEST = "FETCH_SHOES_REQUEST";
export const FETCH_SHOES_FAILURE = "FETCH_SHOES_FAILURE";
export const FETCH_SHOES_SUCCESS = "FETCH_SHOES_SUCCESS";
export const MORE_SHOES_SUCCESS = "FILTER_SHOES_SUCCESS";

export const FETCH_FILTER_SHOES_REQUEST = "FETCH_FILTER_SHOES_REQUEST";
export const FETCH_FILTER_SHOES_FAILURE = "FETCH_FILTER_SHOES_FAILURE";
export const FETCH_FILTER_SHOES_SUCCESS = "FETCH_FILTER_SHOES_SUCCESS";

// FILTER
export const FILTER_SHOES_REQUEST = "FILTER_SHOES_REQUEST";
export const FILTER_SHOES_FAILURE = "FILTER_SHOES_FAILURE";
export const FILTER_SHOES_SUCCESS = "FILTER_SHOES_SUCCESS";

// SEARCH
// export const SEARCH_SHOES_REQUEST = "FILTER_SHOES_REQUEST";
// export const SEARCH_SHOES_FAILURE = "FILTER_SHOES_FAILURE";
// export const SEARCH_SHOES_SUCCESS = "FILTER_SHOES_SUCCESS";
export const CHANGE_SEARCH_FIELD = "HEADER_CHANGE_SEARCH_FIELD";
// export const SEARCH_GET_SHOES = "SEARCH_GET_SHOES";

// CART
